swiftmailer:

    transport: gmail
    username: beinsmart44@gmail.com
    password: pico0123456789
    host: localhost
    port: 465
    encryption: ssl
    auth-mode: login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false

